### PR TITLE
fix migrations stubs location

### PR DESCRIPTION
**Pull request by khanalpride**
Looks like migration stubs are on different location.

### CODE REVIEW

**Comment by freekmurze** [comment]
Seems like the tests are failing for this one.

**Comment by khanalpride** [comment]
@freekmurze 
I just moved the database migration stubs to the location expected by `spatie/laravel-package-tools`

And when I did that, the `php artisan vendor:publish` command run successfully.

I don't think the test have to do anything with that change.

**Comment by khanalpride** [comment]
@freekmurze ah I found the issue.

**Comment by freekmurze** [comment]
Thank you!

**Pull request merged**
