### PR TITLE
expose aggregate_version of StoredEvent

### PR DESCRIPTION
**Pull request by dilab**
As discussed in https://github.com/spatie/laravel-event-sourcing/issues/114

### CODE REVIEW

**Comment by freekmurze** [comment]
Could you add a test that covers the added functionality?

**Comment by dilab** [comment]
It is being tested by other tests.

**Comment by freekmurze** [comment]
By which one?

The test that I am looking for should fail when the code of this PR should be removed.

**Comment by dilab** [comment]
@freekmurze test added. please review.

**Comment by freekmurze** [comment]
Thanks!

**Pull request merged**
