### PR TITLE
add down() to CreateStoredEventsTable

### PR DESCRIPTION
**Pull request by 4n70w4**

### CODE REVIEW

**Comment by freekmurze** [comment]
Thanks, but I generally don't add `down` functions to my migrations.

**Comment by 4n70w4** [comment]
It is necessary for successful execution
`php artisan migration:rollback && php artisan migration`
without errors.

**Comment by riasvdv** [comment]
You can add this function in your own migrations, we generally only use `migrate:fresh`

**Comment by 4n70w4** [comment]
The package description does not say what to use `migrate:fresh` instead `migration:rollback && migration`.

**Comment by 4n70w4** [comment]
I see no objective reason to reject this PR.

**Pull request closed without merging**
